Ajout choix protocole de paiement pour les 3xcb, 4xcb
FLUX-SE/SyliusPayumMoneticoPlugin pull request #23
Opened 2021-08-25 19:54 UTC by imajim

On peut maintenant choisir si il s'agit d'un paiement Classique CB ou être redirigé vers le 3x CB ou 4x CB ... en créant différentes méthodes de paiement
<img width="200" alt="image" src="https://user-images.githubusercontent.com/13310096/130855708-0ae48480-dad3-41b7-a783-240165a5e7ef.png">

<img width="865" alt="image" src="https://user-images.githubusercontent.com/13310096/130855951-e70d016f-7a17-4015-92c2-7fd7e9a9c30c.png">

2021-08-26 08:15 UTC, Prometee requested changes
Merci @imajim,

Je vais fixer la build GitHub Action afin d'obtenir un rapport clair des changements que votre PR engendre, mais à première vu pas mal de modifications d'espaces ou de tabulations ont été comités et ne sont pas nécessaires.
J'ai ajouté quelques commentaires dont il faudra discuter et résoudre afin de finaliser cette PR 😉

2021-08-26 08:15 UTC, Prometee commented on src/Action/ConvertPaymentAction.php
> +        $gatewayConfig = $this->entityManager->getRepository(GatewayConfig::class)->findOneBy(['gatewayName' => $payment->getMethod()->getCode()]);
Il n'est pas nécessaire d'injecter l'`entityManager` ici car la config est accessible depuis le payment :
`$payment->getMethod()->getGatewayConfig()->getConfig()`

2021-08-26 08:15 UTC, Prometee commented on src/Action/ConvertPaymentAction.php
> +            $model->offsetSet('protocole', $gatewayConfig->getConfig()['protocol']);
Il serait plus judicieux de suivre la façon dont les autres attributs de `$model` sont altérés :

```php
if (false === $model->offsetExists('protocole')) {
        $model->offsetSet('protocole', $this->protocolProvider->getProtocol($payment));
}
```

2021-08-26 08:15 UTC, Prometee commented on src/Action/ConvertPaymentAction.php
> +            $model->offsetSet('desactivemoyenpaiement', $protocoles);
Pareil ici ou bien rassembler ces changements dans un provider plus générique `$this->protocoleProvider->provide($paiement, $model)` et opérer tous les tests dans ce provider au lieu d'ici. Afin que cette parti soit `decorable` comme tous les autres `Provider` de cette classe.

2021-08-26 08:15 UTC, Prometee commented on src/Controller/NotifyController.php
> +        Payum            $payum
Il faudrait éviter que des fichiers soient comités pour rien, et je ne pense pas que ces modifications passent les tests ECS, ou PSALM.

2021-08-26 08:15 UTC, Prometee commented on src/Form/Type/MoneticoGatewayConfigurationType.php
> +    static $protocoles = [null => 'Classique', '1euro' => '1euro', '3xcb' => '3xcb', '4xcb' => '4xcb', 'paypal' => 'paypal', 'lyfpay' => 'lyfpay'];
Les labels doivent contenir des clefs de traduction pour pouvoir être traduit.

2021-08-26 08:15 UTC, Prometee commented on src/Resources/config/services/actions.yaml
> +      $entityManager: '@doctrine.orm.entity_manager'
Non nécessaire comme expliqué plus tôt.

2021-08-26 08:15 UTC, Prometee commented on src/Action/ConvertPaymentAction.php
> +use App\Entity\Payment\GatewayConfig;
Le namespace `App` ne doit jamais se trouver dans les sources d'un plugin Sylius (sauf dans le dossier `tests`).

2021-08-26 08:24 UTC, imajim commented on src/Action/ConvertPaymentAction.php
> +use App\Entity\Payment\GatewayConfig;
c'est mon php storm qui a  formaté le code ^^, git je le maitrise pas au top faut dire ^^
En gros je suis en plein test sur les 3x cb et 4x cb de Cofidis pour ajouter en prod ces modes de paiement la semaine prochaine avant les vacances.

2021-08-26 15:54 UTC, imajim commented
j'ai refactorisé le code sur une branche https://github.com/imajim/SyliusPayumMoneticoPlugin/tree/add-protocol
je peux tenter un PR ?

2023-08-12 15:38 UTC, Prometee commented
Désolé pour le retour très(trop) tardif. Si les modifications ont été faite dans une autre branche, alors il faudra créer une nouvelle PR. Ensuite il suffit de faire de nouveaux commits afin de corriger les éventuels retours que je ferais.
Je vais donc clôturer cette PR et vous laisser en créer une autre.

2023-08-12 15:38 UTC, closed without merging